language: node_js
node_js:
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - mkdir -p dist
  - npm install

script:
  - gulp build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  repo: git@github.com:azaitw/azaitw.github.io.git
  on:
    branch: master