language: node_js
node_js:
  - "iojs"
  - "8"

cache:
  directories:
    - "node_modules"

install:
  - mkdir -p dist
  - npm install

before_script:
  - git remote set-url origin "https://${GITHUB_TOKEN}@github.com/azaitw/beardude_2017.git"
  - git config --global user.email "azai.tw@gmail.com"
  - git config --global user.name "Travis-CI"

script:
  - gulp build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master